=== JimGregory-Advania/fauapi-ingestion-test/json-schemas/linked-apis/linked-imported-api-manual-publish.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Manual-publish imported linked API",
	"type": "object",
	"properties": {
		"displayName": {
			"description": "Please enter a friendly display name for this API",
			"type": "string",
			"maxLength": 100,
			"minLength": 3
		},
		"description": {
			"description": "Please enter a brief description of the purpose of this API. This information will be searchable by API consumers and presented as part of search results",
			"type": "string",
			"minLength": 40
		},
		"overview": {
			"description": "This will be visible to API consumers",
			"type": "string"
		},
		"schemaUrl": {
			"description": "Link to the destination of the schema of this API",
			"type": [ "string", "null" ],
			"format": "uri"
		},
		"schemaType": {
			"description": "Specify the schema type",
			"type": [ "string", "null" ],
			"enum": [
				"openapi",
				"openapi+json",
				"wsdl",
				"swagger",
				null
			]
		},
		"backendType": {
			"description": "Allowed values - http, soap, graphql",
			"type": "string",
			"enum": [
				"http",
				"soap",
				"graphql"
			]
		},
		"majorVersion": {
			"description": "Please enter the major version identifier for this API",
			"type": "string",
			"maxLength": 50,
			"minLength": 1,
			"pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
		},
		"visibility": {
			"description": "Allowed values are 'Public', 'Internal', 'Private'",
			"type": "string",
			"enum": [
				"Public",
				"Internal",
				"Private"
			]
		},
		"tags": {
			"description": "Semi-colon delimited set of tags for search",
			"type": "string",
			"pattern": "^([a-zA-Z0-9]+;)+$"
		},
		"classification": {
			"description": "Data exposure classification",
			"type": "string",
			"enum": [
				"Public facing",
				"Across government services",
				"Across departmental services",
				"Within service boundary"
			]
		},
		"serviceLevel": {
			"type": "string"
		},
		"technology": {
			"type": "string"
		},
		"usage": {
			"description": "Describe who can use this API",
			"type": "string"
		},
		"environments": {
			"description": "An array of environments",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string",
						"description": "Only the names 'live', 'staging, and 'dev are allowed'",
						"enum": [
							"live",
							"staging",
							"dev"
						]
					},
					"baseUrl": {
						"type": "string",
						"format": "uri"
					},
					"visibility": {
						"description": "These options are limited to the maximum visibility of the API",
						"type": "string",
						"enum": [
							"Inherit",
							"Private",
							"Public",
							"Internal"
						]
					}
				}
			},
			"minItems": 0,
			"maxItems": 3
		},
		"releases": {
			"type": [ "array", "null" ],
			"items": {
				"type": "object",
				"properties": {
					"isCurrent": {
						"type": "boolean"
					},
					"name": {
						"type": "string",
						"description": "The name of the release"
					},
					"tag": {
						"type": "string",
						"enum": [
							"Live",
							"Alpha",
							"Beta",
							"Planned",
							"Deprecated"
						]
					},
					"availableFrom": {
						"type": "string",
						"format": "date"
					},
					"availableTo": {
						"type": "string",
						"format": "date"
					},
					"notes": {
						"type": "string"
					}
				},
				"required": [
					"isCurrent",
					"name",
					"tag"
				],
				"allOf": [
					{
						"if": {
							"properties": { "isCurrent": { "const": true } }
						},
						"then": {
							"required": [ "availableFrom" ]
						},
						"contains": {
							"properties": {
								"isCurrent": {
									"const": true
								}
							},
							"maxContains": 1
						}
					}
				]
			}
		}
	},
	"required": [
		"displayName",
		"description",
		"backendType",
		"majorVersion",
		"environments"
	],
	"allOf": [
		{
			"properties": {
				"environments": {
					"type": "array",
					"uniqueItems": true,
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							}
						}
					}
				}
			}
		}
	]
}

=== JimGregory-Advania/fauapi-ingestion-test/OT52-example-linked-api-draft-with-metadata.json
{"backendType":"http","classification":"Across government services","description":"This is an example of a valid schema of a linked API that will be set to auto publish","displayName":"OT52-Linked API example draft metadata","environments":[{"Backends":null,"Subscriptions":null,"ApiId":0,"BackendMode":null,"BackendUrl":null,"BaseUrl":"https://valid-base-url.co.uk","CanSubscribe":false,"Enabled":false,"Index":0,"Name":"dev","RequiresApproval":false,"Status":null,"Visibility":"Inherit","Id":0},{"Backends":null,"Subscriptions":null,"ApiId":0,"BackendMode":null,"BackendUrl":null,"BaseUrl":"https://valid-base-url.co.uk","CanSubscribe":false,"Enabled":false,"Index":0,"Name":"staging","RequiresApproval":false,"Status":null,"Visibility":"Inherit","Id":0},{"Backends":null,"Subscriptions":null,"ApiId":0,"BackendMode":null,"BackendUrl":null,"BaseUrl":"https://valid-base-url.co.uk","CanSubscribe":false,"Enabled":false,"Index":0,"Name":"live","RequiresApproval":false,"Status":null,"Visibility":"Private","Id":0}],"majorVersion":"v1","overview":"This message will be presented to the users in the FaUAPI consumption portal","releases":null,"schemaType":null,"schemaUrl":null,"serviceLevel":"24/7","tags":"example;publish;api;","technology":"REST, C#","usage":"Government parties can use it","visibility":"Internal"}

=== JimGregory-Advania/fauapi-ingestion-test/json-schemas/linked-apis/examples/example-linked-api-draft-with-metadata.json
{
    "displayName": "Linked API example publish",
    "description": "This is an example of a valid schema of a linked API that will be set to auto publish",
    "overview": "This message will be presented to the users in the FaUAPI consumption portal",
    "backendType": "http",
    "majorVersion": "v1",
    "visibility": "Internal",
    "tags": "example;publish;api;",
    "classification": "Across government services",
    "serviceLevel": "24/7",
    "technology": "REST, C#",
    "usage": "Government parties can use it",
    "environments": [
        {
            "name": "dev",
            "baseUrl" : "https://valid-base-url.co.uk",
            "visibility" : "Inherit"
        },
        {
            "name": "staging",
            "baseUrl" : "https://valid-base-url.co.uk",
            "visibility" : "Inherit"
        },
        {
            "name": "live",
            "baseUrl" : "https://valid-base-url.co.uk",
            "visibility" : "Private"
        }
    ]
}
